# Generated by Django 4.2.2 on 2023-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofiles',
            name='file_image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
